api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.getRoutes),
    path('content', views.getContent),
    path('team', views.getTeam),
    path('blog', views.getBlog),
    path('gallery', views.getGallery),
    path('contact', views.getContact),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'


urlpatterns = [
    path('', views.blogs, name='blogs'),
    path('blogs/<str:blog_id>/', views.blog_page, name='blog_page'),
]

contact/urls.py
from django.urls import path
from . import views
app_name = 'contact'


urlpatterns = [
    path('', views.contact, name='contact')
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('gallery', views.gallery, name='gallery'),
]

picture_gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('blogs/', include('blog.urls')),
    path('contact/', include('contact.urls')),
    path('api/', include('api.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Blog(models.Model):
    title = models.CharField(max_length=50)
    category = models.CharField(max_length=20)
    image = models.ImageField(upload_to='blog')
    description = models.TextField()
    post_link = models.URLField(blank=True)

    def __str__(self):
        return self.title
    

contact/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField()
    message = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + '-' + self.email

pages/models.py
from django.db import models


class Content(models.Model):
    title = models.CharField(max_length=20)
    category = models.CharField(max_length=20, unique=True)
    description = models.TextField()
    image = models.ImageField(upload_to='content/image')

    def __str__(self):
        return self.title


class Gallery(models.Model):
    name = models.CharField(max_length=30)
    category = models.CharField(max_length=20)
    image = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name + " - " + self.category


class Team(models.Model):
    member_name = models.CharField(max_length=20)
    profile_image = models.ImageField(upload_to='team/profile')
    post = models.CharField(max_length=30)
    facebook_link = models.URLField(blank=True)
    linkedin_link = models.URLField(blank=True)
    instagram_link = models.URLField(blank=True)

    def __str__(self):
        return self.member_name+" - "+self.post

api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from pages.models import Content, Team, Gallery
from blog.models import Blog
from contact.models import Contact
from .serializers import ContentSerializer, TeamSerializer, GallerySerializer, BlogSerializer, ContactSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/content',
        'GET /api/blog',
        'GET /api/gallery',
        'GET /api/team',
        'GET /api/contact',
    ]
    return Response(routes)


@api_view(['GET'])
def getContent(request):

    content = Content.objects.all()
    serializer = ContentSerializer(content, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getTeam(request):

    team = Team.objects.all()
    serializer = TeamSerializer(team, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getGallery(request):

    gallery = Gallery.objects.all()
    serializer = GallerySerializer(gallery, many=True)
    return Response(serializer.data)



@api_view(['GET'])
def getBlog(request):

    blog = Blog.objects.all()
    serializer = BlogSerializer(blog, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getTeam(request):

    team = Team.objects.all()
    serializer = TeamSerializer(team, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getContact(request):

    contact = Contact.objects.all()
    serializer = ContactSerializer(contact, many=True)
    return Response(serializer.data)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.core.paginator import Paginator


def blogs(request):
    bloggings = Blog.objects.all()
    paginator = Paginator(bloggings, 15)
    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    return render(request, 'blog/blog.html', {'page_obj': page_obj})


def blog_page(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    return render(request, 'blog/blog-single.html', {'blog': blog})

contact/views.py
from django.shortcuts import render, redirect
from .models import Contact
from django.contrib import messages


def contact(request):
    if request.method == "POST":
        name = request.POST['name']
        email = request.POST['email']
        message = request.POST['message']
        if Contact.objects.filter(email=email).exists():
            messages.error(request, 'You have already submitted an enquiry...')
        else:
            enquiry = Contact.objects.create(name=name, email=email, message=message)
            enquiry.save()
            messages.success(request, 'Your query has been successfully submitted...')
            return redirect('contact:contact')

    return render(request, 'contact/contact.html')

pages/views.py
from django.shortcuts import render
from .models import Gallery, Team, Content
from django.core.paginator import Paginator


def index(request):
    contents = Content.objects.all()
    return render(request, 'pages/index.html', {'contents': contents})


def about(request):
    teams = Team.objects.all()
    return render(request, 'pages/about.html',{'teams': teams})


def gallery(request):
    images = Gallery.objects.all()

    paginator = Paginator(images, 40)
    page_number = request.GET.get('page')

    page_obj = paginator.get_page(page_number)
    return render(request, 'pages/gallery.html', {'page_obj': page_obj})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>Cassi | Photo Studio HTML Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="Cassi Photo Studio HTML Template">
	<meta name="keywords" content="photo, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}"/>



</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Offcanvas Menu Section -->
	<div class="offcanvas-menu-wrapper">
		<div class="menu-header">
			<a href="{% url 'pages:index' %}" class="site-logo">
				<img src="{% static 'img/logo.png' %}" alt="">
			</a>
			<div class="menu-switch" id="menu-canvas-close">
				<i class="icon_close"></i>
			</div>
		</div>
		<ul class="main-menu">
			<li><a href="{% url 'pages:index' %}">Home</a></li>
			<li><a href="{% url 'pages:gallery' %}">Gallery</a></li>
			<li><a href="{% url 'blog:blogs' %}">Blog</a></li>
			<li><a href="{% url 'pages:about' %}">About</a></li>
			<li><a href="{% url 'contact:contact' %}">Contact</a></li>
		</ul>
		<div class="menu-footer">
			<div class="footer-social">
				<a href="#">Facebook</a>
				<a href="#">Twitter</a>
				<a href="#">Instagram</a>
			</div>
			<div class="copyright"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
              Copyright &copy;<script>document.write(new Date().getFullYear());</script>  All rights reserved | <i class="fa fa-heart"></i> Dipanshu
          </p></div>
		</div>
	</div>
	<!-- Offcanvas Menu Section end -->

	<!-- Header section -->
	<header class="header-section">
		<a href="{% url 'pages:index' %}" class="site-logo">
			<img src="{% static 'img/logo.png' %}" alt="">
		</a>
		<div class="menu-switch" id="menu-canvas-show">
			<i class="icon_menu"></i>
		</div>
	</header>
	<!-- Header section end -->

    {% block content %}
    {% endblock %}
	<!-- Footer section -->
	<footer class="footer-section">
		<div class="footer-social">
			<a href="#">Facebook</a>
			<a href="#">Twitter</a>
			<a href="#">Instagram</a>
		</div>
		<div class="copyright"><p>
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved |<i class="fa fa-heart"></i>Dipanshu
</p></div>
	</footer>
	<!-- Footer section end -->

	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/vendor/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<section class="blog-single-section">
		<div class="blog-single-header set-bg" data-setbg="{{ blog.image.url }}">
			<div class="container">
				<div class="fb-cata">{{ blog.category }}</div>
				<h2>{{ blog.title }}</h2>
				<div class="bs-metas">
					<div class="bs-meta">By Dipanshu</div>
					<div class="bs-meta">February 21, 2019</div>
					<div class="bs-meta">No Comments</div>
				</div>
			</div>
		</div>
		<div class="container">
			<div class="row">
				<div class="col-lg-10 m-auto blog-content">
                    <p>{{ blog.description }}</p>

                    <div class="col-lg-6 mb-5 text-left text-md-right">
                        <div class="post-share">
                            <span>Share:</span>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-google-plus"></i></a>
                            <a href="#"><i class="fa fa-linkedin"></i></a>
                            <a href="#"><i class="fa fa-envelope"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

	</section>

{% endblock %}

templates/blog/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<section class="blog-section">
		<div class="feature-blog set-bg" data-setbg="{% static 'img/blog/big.jpg' %}">
			<div class="container">
				<div class="fb-cata">Nature</div>
				<h2>The Function Of The Logo</h2>
				<p>Cassi – a creative lifestyle photo studio making emotional photography communicate a story. Creative lifestyle photo studio making emotional photography.</p>
				<a href="#" class="site-btn">Read More <i class="arrow_right"></i></a>
			</div>
		</div>
		<div class="blog-post-items">
           {% for blog in page_obj %}
			<div class="blog-col">
				<div class="blog-item set-bg" data-setbg="{{ blog.image.url}}">
					<div class="blog-text">
						<div class="bi-cata">{{ blog.category }}</div>
						<h6><a href="{% url 'blog:blog_page' blog.id %}">{{ blog.title }}</a></h6>
					</div>
				</div>
			</div>
           {% endfor %}
		</div>
        <hr>
        <!-- Pagination links -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>

	</section>

{% endblock %}

templates/contact/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<!-- Contact section -->
	<section class="contact-section">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %} style="color: #4ac1f7">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
		<div class="contact-warp set-bg" data-setbg="{% static 'img/blog/big.jpg' %}">
			<div class="container">
				<div class="row">
					<div class="col-lg-5">
						<div class="contact-info">
							<h4>Information:</h4>
							<div class="ci-item"><i class="icon_phone"></i>(+91)-7388975483</div>
							<div class="ci-item"><i class="icon_mail"></i>dipanshupandey765@gmail.com</div>
						</div>
						<div class="contact-info">
							<h4>Address:</h4>
							<div class="ci-item"><i class="icon_pin"></i>Garhi Kanaura, Lucknoe, U.P. INDIA - 226011</div>
						</div>
					</div>
					<div class="col-lg-7">
						<form class="contact-form" method="POST">
                           {% csrf_token %}
							<label for="y-name">Your Name:</label>
							<input type="text" name="name" id="y-name" required>
							<label for="y-email">Email Address:</label>
							<input type="text" name="email" id="y-email" required>
							<label for="y-msg">Leave A Message:</label>
							<textarea name="message" id="y-msg" required></textarea>
							<button type="submit" class="site-btn">Send Us Now</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Contact section end -->

{% endblock %}

templates/pages/about.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<!-- Page top section -->
	<div class="page-top-section">
		<div class="page-top-warp set-bg" data-setbg="{% static 'img/page-bg-1.jpg' %}">
			<div class="container">
				<div class="row">
					<div class="col-lg-9">
						<h2>Wellcome To Cassi</h2>
						<p>These companies release their own versions of the operating systems with minor changes, and yet always with the same bottom line.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- Page top section end -->

	<!-- About section -->
	<section class="about-section">
		<div class="container">
			<div class="row about-item">
				<div class="col-lg-3">
					<h2>Our Story</h2>
				</div>
				<div class="col-lg-9">
					<div class="ai-text">
						<h4>I was caught up in a web of negativity and needed someone or something to help me to escape.</h4>
						<p>Photographs are a way of preserving a moment in our lives for the rest of our lives. Many of us have at least been tempted at the flashy array of photo printers which seemingly leap off the shelves at even the least tech-savvy. It surely seems old fashioned to talk about 35mm film and non-digital cameras in today’s day and age. To our children, cameras not so feature rich with LCD screens and built in Wi-Fi is as foreign as Atari. However, the innovation of home photo printing is bringing about a new way of preserving our most precious memories. Not only do we have digital copies to keep with us for the rest of our days across hundreds of different archives.</p>
					</div>
				</div>
			</div>
			<div class="row about-item">
				<div class="col-lg-3">
					<h2>What We Do?</h2>
				</div>
				<div class="col-lg-9">
					<div class="ai-text">
						<h4>Audio player software is used to play back sound recordings in one of the many formats available for computers today.</h4>
						<p>Photographs are a way of preserving a moment in our lives for the rest of our lives. Many of us have at least been tempted at the flashy array of photo printers which seemingly leap off the shelves at even the least tech-savvy. It surely seems old fashioned to talk about 35mm film and non-digital cameras in today’s day and age. To our children, cameras not so feature rich with LCD screens and built in Wi-Fi is as foreign as Atari. However, the innovation of home photo printing is bringing about a new way of preserving our most precious memories. Not only do we have digital copies to keep with us for the rest of our days across hundreds of different archives.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- About section end -->

	<!-- Team section -->
	<section class="team-section">
		<div class="container-fluid">
			<div class="text-center text-white mb-5">
				<h2>What We Do?</h2>
			</div>
			<div class="row">
               {% for team in teams %}
				<div class="col-xl-2 col-md-4 col-sm-6 p-0">
					<div class="team-item">
						<img src="{{team.profile_image.url}}" alt="">
						<div class="team-meta">
							<div class="tm-text">
								<h5>{{ team.member_name }}</h5>
								<p>{{ team.post }}</p>
								<div class="tm-social">
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-google-plus"></i></a>
									<a href="#"><i class="fa fa-linkedin"></i></a>
								</div>
							</div>
						</div>
					</div>
				</div>
               {% endfor %}
			</div>
		</div>
	</section>
	<!-- Team section end -->

{% endblock %}

templates/pages/gallery.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
	<!-- Gallery section -->
	<section class="gallery-section">
		<div class="row gallery-gird">
          {% for x in page_obj %}
			<div class="col-lg-4 col-xl-3 col-sm-6">
				<a class="gallery-item fresco" href="{{ x.image.url }}" data-fresco-group="projects">
					<img src="{{x.image.url}}" alt="">
					<div class="gi-text">
						<h4>{{ x.name }}</h4>
						<p>{{ x.category }}</p>
					</div>
				</a>
			</div>
          {% endfor %}
		</div>
        <div class="row">
         <div class="col-md-12" style="align-content: center">
          {% if page_obj.has_other_pages %}
			<!-- Pagination links -->
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
          {% endif %}
         </div>
        </div>

	</section>
	<!-- Gallery section end -->

{% endblock %}

templates/pages/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
	<!-- Hero section -->
	<section class="hero-section">
		<div class="hero-slider owl-carousel">
		  {% for content in contents %}
            <div class="hero-item">
				<div class="hero-text">
					<div class="ht-cata">{{ content.category }}</div>
					<h2>{{ content.title }}</h2>
					<p>{{ content.description }}</p>
					<a href="#" class="ht-btn">See More <i class="fa-solid fa-arrow-right"></i></a>
				</div>
				<div class="hi-bg set-bg" data-setbg="{{ content.image.url }}"></div>
			</div>
          {% endfor %}
		</div>
	</section>
	<!-- Hero section end -->
{% endblock %}